### PR TITLE
Update with Example

### PR DESCRIPTION
**Pull request by tquangsdh20**

### CODE REVIEW

**Review by tquangsdh20 — COMMENTED** [review]
Tittle README change. This is OK

**Comment by mrThanAung** [comment]
from .prettyTTS import _Audio, _Proxy
ModuleNotFoundError: No module named 'prettyTTS.prettyTTS'

**Comment by tquangsdh20** [comment]
> 
> 
> from .prettyTTS import _Audio, _Proxy ModuleNotFoundError: No module named 'prettyTTS.prettyTTS'


Try re-installing with this version: `pip install prettyTTS==1.1.0`

**Comment by mrThanAung** [comment]
> > from .prettyTTS import _Audio, _Proxy ModuleNotFoundError: No module named 'prettyTTS.prettyTTS'
> 
> Try re-installing with this version: `pip install prettyTTS==1.1.0`

Using android termux, still getting errors.

**Comment by tquangsdh20** [comment]
> 
> 
> > > from .prettyTTS import _Audio, _Proxy ModuleNotFoundError: No module named 'prettyTTS.prettyTTS'
> > 
> > 
> > Try re-installing with this version: `pip install prettyTTS==1.1.0`
> 
> Using android termux, still getting errors.

I can't say for sure that whether if it support for your platform. However, Retry it with newest version which's not been released yet. `pip install prettyTTS==1.3.0`

**Pull request merged**
